# Generated by Django 2.1.7 on 2019-03-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('locality_verbose', models.CharField(max_length=200)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(max_length=20, unique=True)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('cuisines', models.CharField(max_length=200)),
                ('average_cost_for_two', models.IntegerField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('has_table', models.BooleanField()),
                ('has_online', models.BooleanField()),
                ('rating', models.FloatField()),
                ('rating_color', models.CharField(max_length=20)),
                ('rating_text', models.CharField(max_length=20)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='restaurantaddress',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.RestaurantDetails'),
        ),
    ]
