# Generated by Django 2.1.7 on 2019-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='restaurant_id',
            field=models.IntegerField(unique=True),
        ),
    ]
