# Generated by Django 2.1.7 on 2019-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20190323_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='average_cost_for_two',
            field=models.IntegerField(),
        ),
    ]
