# Generated by Django 2.1.7 on 2019-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20190323_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantaddress',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
