# Generated by Django 2.1.7 on 2019-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20190323_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantAddress',
        ),
        migrations.DeleteModel(
            name='RestaurantDetails',
        ),
    ]
