# Generated by Django 2.1.7 on 2019-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20190323_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='restaurant_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
