# Generated by Django 2.1.7 on 2019-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20190323_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='has_online',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantdetails',
            name='has_table',
            field=models.CharField(max_length=5),
        ),
    ]
