# Generated by Django 2.1.7 on 2019-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20190323_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='has_online',
            field=models.CharField(max_length=50),
        ),
    ]
