# Generated by Django 2.1.7 on 2019-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_auto_20190323_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='has_table',
            field=models.CharField(max_length=50),
        ),
    ]
