# Generated by Django 2.1.7 on 2019-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_auto_20190323_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='votes',
            field=models.CharField(max_length=20),
        ),
    ]
