# Generated by Django 2.1.7 on 2019-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20190323_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetails',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
