# Generated by Django 2.1.7 on 2019-03-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_auto_20190323_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantaddress',
            name='restaurant_ids',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.RestaurantDetails'),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='country_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='restaurant',
            field=models.CharField(max_length=50),
        ),
    ]
