# Generated by Django 2.1.7 on 2019-03-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20190323_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='restaurant_ids',
        ),
    ]
