# Generated by Django 2.1.7 on 2019-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_remove_restaurantaddress_restaurant_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantaddress',
            name='restaurant',
            field=models.CharField(max_length=200),
        ),
    ]
